apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ant-go 
  janus-idp.io/tekton: ant-go
  backstage.io/kubernetes-id: ant-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ant-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  